name: locale_tags
publish_to: none
description: Local module.

version: 0.0.1+0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flocomotion:
    git:
      url: https://github.com/rtmigo/flocomotion_flutter


dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
